name: Learning Github actions
on: push

jobs:
  job1:
    name: Job 1 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Dir
        run: echo $PWD
      - name: List
        run: ls -la
      - name: Date
        run: date 
      - name: who
        run: whoami
  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Acceptance Test
        run: echo "Acceptance test ... "
  job3:
    name: Job 3
    runs-on: ubuntu-latest
    needs: 
      - job1
      - job2
    steps:
      - name: Unit test 2
        run: echo "Unit testing ... "
  job4:
    name: Job 4
    runs-on: ubuntu-latest
    needs:
      - job1
      - job2
      - job3
    steps:
      - name: Unit test 3
        run: echo "unit test 3"
  Job5:
    name: Job 5
    runs-on: ubuntu-latest
    needs:
      - job1
      - job2
      - job3
      - job4
    steps:
      - name: Azure
        run: echo "Deploy to Azure ... "
      - name: AWS
        run: echo "Deploy to AWS ... "
      - name: GCP
        run: echo "Deploy to GCP ... "
