name: Learning Github actions
on: push

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Dir
        run: echo $PWD
      - name: List
        run: ls -la
      - name: Date
        run: date 
      - name: who
        run: whoami
  test1:
    name: Testing
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Acceptance Test
        run: echo "Acceptance test ... "
  test2:
    name: Test 2
    runs-on: ubuntu-latest
    needs: 
      - build
    steps:
      - name: Unit test 2
        run: echo "Unit testing ... "
  test3:
    name: Test 3
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Unit test 3
        run: echo "unit test 3"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
      - test1
      - test2
      - test3
    steps:
      - name: Azure
        run: echo "Deploy to Azure ... "
      - name: AWS
        run: echo "Deploy to AWS ... "
      - name: GCP
        run: echo "Deploy to GCP ... "
